---
networks:
  base:
    driver: bridge
services:
  dickobrazz:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add: [ "SYS_PTRACE" ]
    command: ["/usr/local/bin/dickobrazz"]
    container_name: dickobrazz_bot
    cpus: '0.25'
    depends_on: [ dickobrazz-redis, dickobrazz-mongo ]
    env_file: [ .env.dev ]
    environment:
      DD_DB_HOST: dickobrazz-mongo
      MONGODB_URI: ${MONGODB_URI}
      RANDOMORG_TOKEN: ${RANDOMORG_TOKEN}
      REDIS_ADDRESS: ${REDIS_ADDRESS}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TZ: ${TZ}
    logging:
      driver: local
      options:
        max-file: '3'
        max-size: 10m
    mem_limit: 256m
    mem_reservation: 64m
    networks: [ base ]
    restart: unless-stopped
    security_opt: [ "seccomp:unconfined" ]
    volumes:
      - .:/workspace:cached
  dickobrazz-mongo:
    command: ["--wiredTigerCacheSizeGB", "0.25"]
    container_name: dickobrazz-mongo
    cpus: '0.5'
    env_file: [ .env.dev ]
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      TZ: ${TZ}
    image: mongo:8.2
    logging:
      driver: local
      options:
        max-file: '3'
        max-size: 10m
    mem_limit: 512m
    mem_reservation: 256m
    networks: [ base ]
    ports: [ "27017:27017" ]
    restart: unless-stopped
    volumes:
      - dickobrazz-mongo-data:/data/db
  dickobrazz-redis:
    command: >
      redis-server --port 6379
      --loglevel warning
      --save 20 1
      --requirepass ${REDIS_PASSWORD}
    container_name: dickobrazz-redis
    cpus: '0.5'
    env_file: [ .env.dev ]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      TZ: ${TZ}
    image: redis:8.2-alpine
    logging:
      driver: local
      options:
        max-file: '3'
        max-size: 10m
    mem_limit: 256m
    mem_reservation: 128m
    networks: [ base ]
    ports: [ "6379:6379" ]
    restart: unless-stopped
    volumes:
      - dickobrazz-redis-data:/data
volumes:
  dickobrazz-mongo-data:
    driver: local
  dickobrazz-redis-data:
    driver: local