# syntax=docker/dockerfile:1

FROM alpine:latest as certs
RUN apk --update add ca-certificates

FROM golang:1.23.4 AS builder
RUN go install github.com/go-delve/delve/cmd/dlv@latest
COPY go.mod go.sum ./
ENV GOPATH=""
RUN go mod download
COPY *.go ./
COPY *.env ./
COPY .version ./
COPY .git ./
COPY application/*.go ./application/
RUN go build -o /app/dickobot -a -installsuffix cgo -gcflags "all=-N -l" -tags timetzdata -ldflags="-X application.application.Version="$(cat .version)" -X application.application.BuildAt="$(date +%Y-%m-%d_%H:%M:%S)" -X application.application.BuildRv="$(git describe --always --long)""
RUN chmod +x /app/dickobot

FROM busybox
EXPOSE 10000
COPY --from=certs /etc/ssl/certs /etc/ssl/certs
COPY --from=builder /app/dickobot dickobot
COPY --from=builder /go/bin/dlv /
CMD ["/dlv", "--listen=:10000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "./dickobot"]