FROM golang:1.25.4-alpine3.21

WORKDIR /workspace

RUN apk --no-cache add \
    git \
    build-base \
    pkgconfig \
    ca-certificates \
    tzdata \
    curl \
    wget \
    bash \
    && update-ca-certificates

ENV CGO_ENABLED=1 \
    GOMODCACHE=/go/pkg/mod \
    GOCACHE=/home/devuser/.cache/go-build

RUN adduser -D -s /bin/bash -G root devuser \
    && mkdir -p /go/bin /go/pkg/mod /home/devuser/.cache/go-build \
    && chown -R devuser:root /go /home/devuser/.cache

USER devuser

RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest \
    && go install github.com/air-verse/air@latest

CMD ["sleep", "infinity"]
